FROM python:3.11-slim

WORKDIR /app

COPY requirements.api.txt /app/requirements.api.txt
RUN pip install --no-cache-dir -r /app/requirements.api.txt

COPY api /app/api
COPY models /app/models

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]   